### ISSUE TITLE
I think `subscribe` is in a code example, when it should be `unsubscribe`

### ISSUE THREAD

**Issue by kofno** [pakyow/docs#27]
Then line is here: https://github.com/pakyow/docs/blame/master/realtime/_overview.md#L39

**Comment by bryanp** [comment]
Yep, you're correct. Thanks for reporting!

**Comment by bryanp** [comment]
Fixed [here](https://github.com/pakyow/docs/commit/4b1603cd96fba071dd76f8fc83b8f76743d04147).
